import Head from "next/head";
import { useState } from "react";
import { Inter } from "next/font/google";
import {
  DangerButton,
  TextButton,
  PrimaryButton,
  SecondaryButton,
  TertiaryButton,
} from "@/components/Buttons";
import { SearchField } from "@/components/Fields";

import { PrimaryPill, SecondaryPill, TertiaryPill } from "@/components/Pills";

import { HorizontalSelection, VerticalSelection } from "@/components/Selection";

import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [theme, setTheme] = useState("theme-light");

  function toggleTheme() {
    if (theme === "theme-light") {
      document.body.classList.remove("light");

      setTheme("theme-dark");
    } else {
      document.body.classList.add("light");
      setTheme("theme-light");
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          marginLeft: "20px",
        }}
      >
        <button
          style={{
            position: "fixed",
            Top: "0",
            right: "0vw",
          }}
          className={styles.buttons}
          onClick={toggleTheme}
        >
          Toggle Theme
        </button>
        <div
          style={{
            display: "flex",
            gap: "1rem",
            marginTop: "1rem",
            flexDirection: "column",
          }}
        >
          <h1>Heading h1</h1>

          <h2>Heading h2</h2>

          <h3>Heading h3</h3>

          <h4>Heading h4</h4>

          <h5>Heading h5</h5>

          <h6>Heading h6</h6>

          <p style={{ maxWidth: "500px" }}>
            Paragraph Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Consectetur, modi. Consequatur est dicta hic obcaecati deserunt!
            Quibusdam a perferendis ad incidunt deleniti laborum adipisci sunt
            alias, veniam voluptates? Rerum est reiciendis beatae illum
            quibusdam! Distinctio esse facere, totam incidunt sint provident
            unde quia rem blanditiis autem ex sed illo architecto!
          </p>

          <div style={{ width: "250px" }}>
            <PrimaryButton onClick={() => console.log("clicked")}>
              <span>😋</span>
              <span>PrimaryButton</span>
            </PrimaryButton>
          </div>

          <div style={{ width: "250px" }}>
            <SecondaryButton onClick={() => console.log("clicked")}>
              <span>SecondaryButton</span>
            </SecondaryButton>
          </div>

          <div style={{ width: "250px" }}>
            <TertiaryButton>
              <span>TertiaryButton</span>
            </TertiaryButton>
          </div>

          <div style={{ width: "250px" }}>
            <DangerButton>
              <span>DangerButton</span>
            </DangerButton>
          </div>

          <div style={{ width: "250px" }}>
            <TextButton>
              <span>TextButton</span>
            </TextButton>
          </div>

          <PrimaryPill>
            <span>PrimaryPill</span>
          </PrimaryPill>

          <SecondaryPill>
            <span>SecondaryPill</span>
          </SecondaryPill>

          <TertiaryPill>
            <span>TertiaryPill</span>
            <span>🐓</span>
          </TertiaryPill>

          <div
            style={{
              width: "85%",
              display: "flex",
            }}
          >
            <HorizontalSelection>
              <span onClick={() => console.log("clicked")}>Selection1</span>
              <span>
                <span>🌼</span>
                Horizontal
              </span>
              <span>Selection</span>
              <span>Selection3</span>
            </HorizontalSelection>
          </div>

          <div
            style={{
              height: "70vh",
            }}
          >
            <VerticalSelection>
              <span>Selection1</span>
              <span onClick={() => console.log("clicked")}>
                <span>🦥</span>
                Verical
              </span>
              <span>Selection</span>
              <span>Selection3</span>
            </VerticalSelection>
          </div>

          <form>
            <SearchField
              onClick={() => console.log("clicked")}
              onInput={(e) => console.log(e.target.value)}
            />
          </form>

          <br />
        </div>
      </div>
    </>
  );
}
